export const TOILET_FACTS = Object.freeze([
  {
    id: 'water-trap',
    category: 'Plumbing',
    fact: 'The curved pipe under a toilet is called a trap. It keeps a small amount of water in the bend, which helps block sewer gases from coming back into the room.',
    question: 'What is the main job of the water sitting in a toilet trap?',
    options: ['Make the toilet louder', 'Block sewer gases', 'Warm the toilet bowl', 'Store drinking water'],
    correctIndex: 1,
    explanation: 'The water seal in the trap helps stop sewer gases from travelling back through the drain.',
  },
  {
    id: 'airplane-vacuum',
    category: 'Engineering',
    fact: 'Airplane toilets use a vacuum system. A rush of air helps move waste away, so they can use much less water than a typical home toilet.',
    question: 'What mainly moves waste in an airplane toilet?',
    options: ['A vacuum and rushing air', 'A spinning brush', 'A heating element', 'A conveyor belt'],
    correctIndex: 0,
    explanation: 'Airplane toilets rely on vacuum pressure and fast-moving air rather than a large flush of water.',
  },
  {
    id: 'space-airflow',
    category: 'Space',
    fact: 'Space toilets use carefully directed airflow because microgravity does not pull waste downward the way gravity does on Earth.',
    question: 'Why do space toilets need airflow?',
    options: ['To make the toilet smell like flowers', 'Because water cannot exist in space', 'Because gravity does not pull waste downward normally', 'To make astronauts float faster'],
    correctIndex: 2,
    explanation: 'In microgravity, airflow helps guide waste where it needs to go.',
  },
  {
    id: 'helpful-microbes',
    category: 'Science',
    fact: 'Wastewater treatment plants often use helpful microorganisms. These tiny living things can break down some of the organic material in wastewater.',
    question: 'What can helpful microorganisms do in wastewater treatment?',
    options: ['Turn pipes into metal', 'Break down organic material', 'Make wastewater freeze', 'Create toilet paper'],
    correctIndex: 1,
    explanation: 'Microorganisms are an important part of biological wastewater treatment.',
  },
  {
    id: 'gravity-sewers',
    category: 'Engineering',
    fact: 'Many sewer pipes are built with a slight slope. That lets gravity help carry wastewater downhill toward larger sewers or treatment systems.',
    question: 'Why are many sewer pipes installed on a slight slope?',
    options: ['To make them look longer', 'So gravity helps move wastewater', 'To keep them warmer', 'So they can hold more air'],
    correctIndex: 1,
    explanation: 'A small slope allows gravity to keep wastewater moving.',
  },
  {
    id: 'cistern',
    category: 'Plumbing',
    fact: 'The tank on many toilets is called a cistern. It stores water so it is ready to be released quickly during a flush.',
    question: 'What does a toilet cistern mainly do?',
    options: ['Stores flush water', 'Stores soap', 'Heats the bathroom', 'Measures body weight'],
    correctIndex: 0,
    explanation: 'The cistern holds water until the toilet is flushed.',
  },
  {
    id: 'dual-flush',
    category: 'Water',
    fact: 'A dual-flush toilet gives two flushing choices, usually so a smaller amount of water can be used when a full flush is not needed.',
    question: 'Why does a dual-flush toilet have two flush options?',
    options: ['To play two sounds', 'To save water when possible', 'To change the bowl colour', 'To clean the seat automatically'],
    correctIndex: 1,
    explanation: 'The smaller flush can reduce water use for lighter flushing needs.',
  },
  {
    id: 'soap-molecules',
    category: 'Hygiene',
    fact: 'Soap molecules have one part that is attracted to water and another part that can interact with oils and grease. That helps loosen grime so it can be rinsed away.',
    question: 'How does soap help clean your hands?',
    options: ['It freezes germs', 'It helps lift oils and grime so they can rinse away', 'It turns water into air', 'It makes skin waterproof'],
    correctIndex: 1,
    explanation: 'Soap helps surround and lift oily dirt so water can carry it away.',
  },
  {
    id: 'dry-hands',
    category: 'Hygiene',
    fact: 'Drying your hands after washing matters because wet hands can transfer microbes more easily than properly dried hands.',
    question: 'Why is drying your hands after washing useful?',
    options: ['Wet hands can transfer microbes more easily', 'Dry hands glow in the dark', 'It makes soap stronger later', 'It changes your fingerprints'],
    correctIndex: 0,
    explanation: 'Drying is part of effective hand hygiene.',
  },
  {
    id: 'blackwater-greywater',
    category: 'Water',
    fact: 'Wastewater from toilets is often called blackwater. Water from showers or sinks may be called greywater, depending on the local system and rules.',
    question: 'Which type of wastewater usually includes toilet waste?',
    options: ['Rainwater', 'Blackwater', 'Steamwater', 'Bluewater'],
    correctIndex: 1,
    explanation: 'Toilet wastewater is commonly classified as blackwater.',
  },
  {
    id: 'composting-toilet',
    category: 'Environment',
    fact: 'Composting toilets can operate with little or no flushing water. They manage waste differently from a normal sewer-connected toilet.',
    question: 'What is unusual about many composting toilets?',
    options: ['They use little or no flushing water', 'They must be made of glass', 'They only work in airplanes', 'They need seawater'],
    correctIndex: 0,
    explanation: 'Composting toilets are designed to manage waste without a conventional water flush.',
  },
  {
    id: 'swirl-myth',
    category: 'Myth Busting',
    fact: 'The direction water swirls in a toilet is controlled mostly by the bowl shape and water jets. Your hemisphere does not reliably decide the swirl direction.',
    question: 'What mostly controls the swirl direction in a toilet bowl?',
    options: ['The day of the week', 'The bowl design and water jets', 'The Moon', 'The hemisphere alone'],
    correctIndex: 1,
    explanation: 'Toilet design has a much bigger effect than the Coriolis effect at that small scale.',
  },
  {
    id: 'flush-flow',
    category: 'Engineering',
    fact: 'A toilet flush releases water quickly. That rapid flow helps push waste through the trap and into the drainpipe.',
    question: 'Why is flush water released quickly?',
    options: ['To create enough flow to move waste through the trap', 'To cool the room', 'To charge a battery', 'To dry the bowl'],
    correctIndex: 0,
    explanation: 'The fast-moving water creates the flow needed to carry waste into the drain.',
  },
  {
    id: 'screens',
    category: 'Wastewater',
    fact: 'At many wastewater treatment plants, screens are one of the first steps. They catch larger objects before the water moves to later treatment stages.',
    question: 'What do screens at a wastewater plant remove first?',
    options: ['Large objects and debris', 'All dissolved salt', 'Every single bacterium', 'Oxygen'],
    correctIndex: 0,
    explanation: 'Screens protect later equipment by catching larger debris.',
  },
  {
    id: 'settling',
    category: 'Wastewater',
    fact: 'In settling tanks, wastewater is slowed down so heavier solids can sink to the bottom and be separated.',
    question: 'What happens to many heavier solids in a settling tank?',
    options: ['They float into the sky', 'They sink to the bottom', 'They turn into glass', 'They disappear instantly'],
    correctIndex: 1,
    explanation: 'Slowing the water gives heavier particles time to settle.',
  },
  {
    id: 'recycled-water',
    category: 'Water',
    fact: 'After enough treatment, some wastewater can be reused for jobs such as irrigation or industry, depending on local safety standards.',
    question: 'What can happen to some properly treated wastewater?',
    options: ['It may be reused for suitable purposes', 'It always becomes ocean water instantly', 'It can never be used again', 'It must be frozen'],
    correctIndex: 0,
    explanation: 'Water reuse can reduce demand for fresh water when treatment and local standards allow it.',
  },
  {
    id: 'soap-v-water',
    category: 'Hygiene',
    fact: 'Washing with soap is generally more effective than rinsing with water alone because soap helps lift oils, dirt and microbes from the skin.',
    question: 'Why is soap useful during handwashing?',
    options: ['It helps remove oils, dirt and microbes', 'It makes water heavier', 'It changes your hand size', 'It replaces the need to rinse'],
    correctIndex: 0,
    explanation: 'Soap helps loosen material from the skin so it can be rinsed away.',
  },
  {
    id: 'twenty-seconds',
    category: 'Hygiene',
    fact: 'A common handwashing recommendation is to scrub with soap for about 20 seconds before rinsing.',
    question: 'About how long is a commonly recommended hand-scrubbing time?',
    options: ['2 seconds', '5 seconds', '20 seconds', '5 minutes'],
    correctIndex: 2,
    explanation: 'About 20 seconds gives enough time to clean all areas of the hands carefully.',
  },
  {
    id: 'lid-droplets',
    category: 'Hygiene',
    fact: 'Flushing can create tiny droplets in the air. If a toilet has a lid, closing it before flushing can help reduce how many droplets escape upward.',
    question: 'What can closing a toilet lid before flushing help reduce?',
    options: ['Tiny droplets escaping upward', 'The number of tiles in the room', 'The water temperature', 'The size of the toilet'],
    correctIndex: 0,
    explanation: 'A closed lid can act as a barrier to some droplets produced during flushing.',
  },
  {
    id: 'bidet',
    category: 'Design',
    fact: 'A bidet cleans with water. Depending on how it is used, it can reduce the amount of toilet paper needed.',
    question: 'What does a bidet mainly use for cleaning?',
    options: ['Sand', 'Water', 'Paint', 'Steam only'],
    correctIndex: 1,
    explanation: 'Bidets use a stream of water for cleaning.',
  },
  {
    id: 'vacuum-sound',
    category: 'Engineering',
    fact: 'Vacuum toilets can sound very loud because air moves through the system extremely quickly when the valve opens.',
    question: 'Why can a vacuum toilet sound so loud?',
    options: ['Fast-moving air rushes through the system', 'A bell rings inside it', 'The bowl is made of drums', 'It plays a recording'],
    correctIndex: 0,
    explanation: 'The sudden movement of air creates the characteristic loud sound.',
  },
  {
    id: 'plumbing-vents',
    category: 'Plumbing',
    fact: 'Plumbing systems use vent pipes to help air move through the drainage system and keep pressure more balanced.',
    question: 'What is one job of plumbing vent pipes?',
    options: ['Help air move and balance pressure', 'Store toilet paper', 'Heat the sewer', 'Colour the water'],
    correctIndex: 0,
    explanation: 'Vents help drains work properly by allowing air and pressure to move through the system.',
  },
  {
    id: 'dry-trap',
    category: 'Plumbing',
    fact: 'If a drain is unused for a long time, the water in its trap can evaporate. Without that water seal, unpleasant sewer smells may enter the room.',
    question: 'Why can an unused drain sometimes begin to smell?',
    options: ['The trap water may have evaporated', 'The pipe becomes magnetic', 'The room loses gravity', 'The drain grows warmer than the Sun'],
    correctIndex: 0,
    explanation: 'The trap needs water to maintain its gas-blocking seal.',
  },
  {
    id: 'toilet-paper-breakdown',
    category: 'Sewers',
    fact: 'Toilet paper is designed to break apart relatively quickly in water. Many wipes are much tougher and may not break down the same way.',
    question: 'Which is designed to break apart relatively quickly in toilet water?',
    options: ['A plastic bag', 'Toilet paper', 'A towel', 'A wet wipe package'],
    correctIndex: 1,
    explanation: 'Toilet paper is made to disperse more readily in water than many other paper-like products.',
  },
  {
    id: 'wipes-blockages',
    category: 'Sewers',
    fact: 'Many wet wipes do not break apart like toilet paper and can contribute to sewer blockages, even when they look soft.',
    question: 'Why can wet wipes cause problems in sewers?',
    options: ['They may not break apart easily', 'They evaporate too fast', 'They turn into metal', 'They make water glow'],
    correctIndex: 0,
    explanation: 'Tough wipes can stay intact and catch on other material inside pipes.',
  },
  {
    id: 'fatbergs',
    category: 'Sewers',
    fact: 'A fatberg is a hard mass that can form in sewers when fats, oils and grease combine with items that should not have been flushed.',
    question: 'What helps form a fatberg?',
    options: ['Fats, oils, grease and non-flushable items', 'Clean rainwater only', 'Fresh air', 'Ice cubes only'],
    correctIndex: 0,
    explanation: 'Fatbergs build up when sticky fats and unsuitable flushed items collect together.',
  },
  {
    id: 'biogas',
    category: 'Energy',
    fact: 'Some wastewater treatment plants use digesters where microorganisms break down sludge and produce biogas that can be used as an energy source.',
    question: 'What useful product can some wastewater digesters make?',
    options: ['Biogas', 'Glass', 'Salt crystals only', 'Plastic pipes'],
    correctIndex: 0,
    explanation: 'Anaerobic digestion can produce methane-rich biogas from organic material.',
  },
  {
    id: 'uv-treatment',
    category: 'Science',
    fact: 'Some treatment plants use ultraviolet light as a disinfection step because UV can damage the genetic material of many microorganisms.',
    question: 'Why might a wastewater plant use ultraviolet light?',
    options: ['For disinfection', 'To make the pipes taller', 'To freeze the water', 'To create soap bubbles'],
    correctIndex: 0,
    explanation: 'UV treatment can reduce microorganisms without adding a chemical disinfectant.',
  },
  {
    id: 'two-pipe-systems',
    category: 'Plumbing',
    fact: 'Homes use different pipe systems for clean water coming in and wastewater going out. Keeping these flows separate is an important part of safe plumbing.',
    question: 'Why are clean-water pipes and wastewater pipes kept separate?',
    options: ['For safer water and sanitation', 'So pipes can have different colours', 'To make rooms louder', 'So toilets can float'],
    correctIndex: 0,
    explanation: 'Separating supply water from wastewater protects hygiene and water quality.',
  },
  {
    id: 'flush-valve',
    category: 'Engineering',
    fact: 'On many tank-style toilets, pressing the handle or button opens a valve so stored water can rush from the tank into the bowl.',
    question: 'What happens when the flush valve opens?',
    options: ['Stored water rushes into the bowl', 'The toilet moves across the floor', 'The drain seals forever', 'The seat becomes a pump'],
    correctIndex: 0,
    explanation: 'Opening the valve releases the stored flush water quickly.',
  },
]);

function hashDateKey(dateKey = '') {
  let hash = 2166136261;
  for (const char of String(dateKey)) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash >>> 0);
}

export function getDailyToiletFact(dateKey) {
  const index = hashDateKey(dateKey) % TOILET_FACTS.length;
  return TOILET_FACTS[index];
}
